### ISSUE TITLE
Support lower sampling rate

### ISSUE THREAD

**Issue by marki555** [antirez/dump1090#65]
Hello,
I wanted to lower the CPU usage on Raspbbery Pi by using lower sampling rate in rtlsdr, but it seems all the decoding is hardcoded for 2 MHz and dump1090 did not detect any aircraft with lower sample rate.

If I understand the sample rate correctly, it means how much data around the tuned frequency we see at once. So it should be 1090 MHz +/- 2 MHz. I guess Mode S data are much narrower, so we shouldn't need to process the whole 2 MHz. Or is there any other option how to decrease the CPU usage?

**Comment by yuvadm** [comment]
There doesn't seem to be any issue here, closing.

**Comment by antirez** [comment]
The best thing to do to lower CPU usage in dump1090 is to add a new switch for more robust preamble detection in order to avoid using time in frames that are likely due to noise or too weak anyway to be decoded in a consistent way. With such a change you get maybe a few less ADSB messages, but the CPU usage may be lowered in a significant way.
